<div class="jumbotron">
	<div class="container">
		<h1 class="display-3">Framework BlockPC</h1>
		<div class="estado" style="display:none;">
			<p class="small">[BROWSER]</p>
			<span class="small float-right mt-1">[HOY]</span>
		</div>
		<div><a class="btn btn-primary btn-sm" href="[URL_ESTADO]" id="estado" role="button">Estado actual &raquo;</a></div>
	</div>
</div>
<div class="container">
	<div class="row">
		<div class="col">
			<h1>[TITULO]</h1>
		</div>
		<div class="col">
			<h1>[HOY]</h1>
		</div>
	</div>
</div>
