<nav class="container navbar navbar-expand-lg navbar-light bg-light">
	<a class="navbar-brand" href="[URL_BASE]instalador">Instalación BlockPC</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	<span class="navbar-toggler-icon"></span>
	</button>
	<div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class="navbar-nav justify-content-center">
			<li class="nav-item">
				<a class="nav-link" href="[URL_BASE]instalador">Inicio</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="[URL_BASE]instalador/instalacion">Instalación</a>
			</li>
			<li class="nav-item">
				<a class="nav-link active" href="#">Configuración</a>
			</li>
			<li class="nav-item dropdown">
				<a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Módulos</a>
				<div class="dropdown-menu">
					<a class="dropdown-item" href="[URL_BASE]instalador/grupos">Grupos</a>
					<a class="dropdown-item" href="[URL_BASE]instalador/modulos">Módulos</a>
					<div class="dropdown-divider"></div>
					<a class="dropdown-item" href="[URL_BASE]instalador/controladores">Controladores</a>
					<a class="dropdown-item" href="[URL_BASE]instalador/modelos">Módelos</a>
					<a class="dropdown-item" href="[URL_BASE]instalador/vistas">Vistas</a>
				</div>
			</li>
			<li class="nav-item dropdown">
				<a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Templates</a>
				<div class="dropdown-menu">
					<a class="dropdown-item" href="[URL_BASE]instalador/plantilla">Clase Plantilla</a>
					<a class="dropdown-item" href="[URL_BASE]instalador/vista">Clase Vista</a>
				</div>
			</li>
		</ul>
	</div>
</nav>
<div class="container">
    <h2><i class="fa fa-cogs mr-1"></i> Sobre la Configuración</h2>
</div>